# my global config
global:
  scrape_interval: 15s
  evaluation_interval: 30s

scrape_configs:
  - job_name: kafka_exports

    static_configs:
      - targets: ["kafka-1:9101", "kafka-2:9102", "kafka-3:9103"]

  - job_name: prometheus
    metrics_path: /metrics
    static_configs:
      - targets:
          - localhost:9090