[rabbitmq_nodes]
node-1 ansible_host=127.0.0.1 ansible_port=2221
node-2 ansible_host=127.0.0.1 ansible_port=2222
node-3 ansible_host=127.0.0.1 ansible_port=2223

[galera_nodes]
node-1 ansible_host=127.0.0.1 ansible_port=2221
node-2 ansible_host=127.0.0.1 ansible_port=2222
node-3 ansible_host=127.0.0.1 ansible_port=2223

[consul_nodes]
node-1 ansible_host=127.0.0.1 ansible_port=2221
node-2 ansible_host=127.0.0.1 ansible_port=2222
node-3 ansible_host=127.0.0.1 ansible_port=2223

[all_nodes:children]
rabbitmq_nodes